###############################
### Analysis config options ###
###############################

genomes:
  human:
    accession: "GCF_000001405.40"
    genome_name: "human_GRCh38"
    pattern_match: "Homo_sapiens"
    chrom_sizes_file: "data/genome/human.chrom.sizes"       
  cmv:
    accession: "GCA_027926625.1"
    genome_name: "cmv_tb40E"
    chr_name_change: "KF297339.1"
    pattern_match: "KF297339.1"
    chrom_sizes_file: "data/genome/cmv.chrom.sizes"
  spikein:
    accession: "GCF_023101765.2"
    genome_name: "spodoptera"
    pattern_match: "Spodoptera"

fastq_sample:

genomes_to_extact: 
  - cmv 
  - human

fastq:
  directory: "data/fastq/"

bowtie2:
  index: "data/genome/human_tb40E_spodoptera_combined_genome" # reference genome
  umi_size: 8 # size of umi to trim from reads prior to align
  paired_options: "--fr --no-discordant" # options for paired end alignment
  additional_params: ""  # additional bowtie2 parameters 

create_track:
  track_type: "bw" # choose bw for bigwig or bg for bedgraph
  binsize: 1 # size of bedgraph bins
  bedgraph_definition_line: "track type=bedGraph"